import assert from 'node:assert/strict';
import {initialStore,load,save,advance,transition,recommend,managerSummary,providers,KEY,STAGES} from '../crm-store.js';
const NOW='2026-09-23T12:00:00.000Z';
const data=new Map(),storage={getItem:key=>data.get(key),setItem:(key,value)=>data.set(key,value)};
let store=load(storage,NOW);
assert.equal(store.opportunities.length,8);
assert.deepEqual(STAGES,['Lead','Qualified','Proposal','Negotiation','Won','Lost']);
assert.equal(store.opportunities[0].stage,'Lead');
assert.equal(advance(store,'o1','Demo reviewer',NOW).stage,'Qualified');
assert.equal(advance(store,'o1','Demo reviewer',NOW).stage,'Proposal');
assert.equal(advance(store,'o1','Demo reviewer',NOW).stage,'Negotiation');
assert.equal(advance(store,'o1','Demo reviewer',NOW).stage,'Won');
assert.throws(()=>advance(store,'o1','Demo reviewer',NOW),/INVALID_TRANSITION/);
assert.equal(store.audit.length,4);
assert.equal(store.opportunities[0].activities.length,5);
assert.throws(()=>transition(store,'o2','Won','Reviewer','skip',NOW),/INVALID_TRANSITION/);
assert.throws(()=>transition(store,'o2','Lost','Reviewer','',NOW),/HUMAN_REASON_REQUIRED/);
assert.equal(transition(store,'o2','Lost','Reviewer','Fictional lost reason',NOW).stage,'Lost');
assert.equal(store.audit.at(-1).reason,'Fictional lost reason');
assert.throws(()=>advance(store,'missing'),/NOT_FOUND/);
save(storage,store);
assert.equal(load(storage,NOW).opportunities[0].stage,'Won');
assert.ok(data.has(KEY));
const base=initialStore(NOW);
assert.equal(recommend(base.opportunities[1],NOW).code,'STALE');
assert.equal(recommend(base.opportunities[3],NOW).code,'PROPOSAL_WAIT');
assert.equal(recommend(base.opportunities[2],NOW).code,'MISSING_DECISION_MAKER');
assert.equal(recommend(base.opportunities[4],NOW).code,'HIGH_VALUE');
assert.equal(recommend(base.opportunities[6],NOW).code,'CLOSED');
const manager=managerSummary(base,NOW);
assert.equal(manager.counts.Lead,1);
assert.equal(manager.counts.Won,1);
assert.equal(manager.counts.Lost,1);
assert.equal(manager.pipeline,269000);
assert.equal(manager.stale,1);
assert.ok(manager.forecast>0);
assert.equal(providers.mock.state,'MOCK');
assert.match(providers.mock.suggest(base.opportunities[1],NOW),/17 days/);
assert.equal(providers.external.state,'NOT_CONFIGURED');
assert.throws(()=>providers.external.suggest(),/NOT_CONFIGURED/);
const legacy={version:1,opportunities:[{id:'old','title':'Legacy synthetic','account':'Old demo','stage':'Solution fit','action':'Review','updated':'Today'}],audit:[]};
data.set(KEY,JSON.stringify(legacy));
assert.equal(load(storage,NOW).opportunities[0].stage,'Qualified');
console.log('CRM stage, persistence, migration, recommendations and manager summary passed.');
